version     = "0.1.0"
author      = "Softmax"
description = "Four thruster skimmers feel for drifting plankton; nothing is caught unless two of them touch it at the same instant."
license     = "MIT"

srcDir = "src"

requires "nim >= 2.2.4"
requires "bitworld >= 0.1.0"
requires "pixie"
requires "mummy >= 0.4.7"
requires "curly >= 1.1.1"
requires "whisky >= 0.1.3"
requires "supersnappy >= 2.1.3"
requires "zippy"
requires "flatty >= 0.3.4"
